name: my_expenses
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.0
  date_format: ^2.0.9
  intl: ^0.19.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  provider: ^6.1.2
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  flutter_staggered_grid_view: ^0.7.0
  month_picker_dialog: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/wallet-8184645_1280.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/wallet-8184645_1280.png
    - lib/assets/images/dart.png
    - lib/assets/images/—Pngtree—man avatar image for profile_13001882.png
    - lib/assets/images/go.png
    - lib/assets/images/vue.png
    - lib/assets/images/graph.png
    - lib/assets/images/moneybag.png
    - lib/assets/images/—Pngtree—money bag vector_9168976.png
    - lib/assets/images/google.png
